apiVersion: v1
kind: Service
metadata:
  name: mct-code-review
  namespace: inthewild
  labels:
    app: mct-code-review
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3015
    protocol: TCP
    name: http
  selector:
    app: mct-code-review
---
