apiVersion: v1
kind: Service
metadata:
  name: mct-payment
  namespace: inthewild
  labels:
    app: mct-payment
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: mct-payment
---
