apiVersion: v1
kind: Service
metadata:
  name: mct-ab-testing
  namespace: inthewild
  labels:
    app: mct-ab-testing
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3020
    protocol: TCP
    name: http
  selector:
    app: mct-ab-testing
---
